stages:
  - test
  - deploy

lint-backend:
  stage: test
  script:
    - cd admin
    - poetry install --with dev
    - poetry run ruff check .

test-backend:
  stage: test
  script:
    - cd admin
    - poetry install --with test
    - poetry run pytest

deploy-backend:
  stage: deploy
  script:
    - cd admin
    # Aquí irían los comandos de despliegue, como por ejemplo una conexión SSH o un comando de Heroku
    # Pega aquí el comando que tu equipo usa para desplegar.
    # Si no lo sabes, pregúntale a un compañero.
  environment:
    name: produccion